various cleanups

diff --git a/tools/azure-pipelines/jobs-template.yml b/tools/azure-pipelines/jobs-template.yml
--- a/tools/azure-pipelines/jobs-template.yml
+++ b/tools/azure-pipelines/jobs-template.yml
@@ -141,9 +141,10 @@ jobs:
       ./tools/azure-pipelines/unpack_build_artifact.sh
       export DEBUG_FILES="$AGENT_TEMPDIRECTORY/debug_files"
       echo "##vso[task.setvariable variable=DEBUG_FILES]$DEBUG_FILES"
-      mkdir -p $DEBUG_FILES || { echo "FAILURE: cannot create log directory '${DEBUG_FILES}'." ; exit 1; }
-      ${{parameters.environment}} ./tools/ci/test_controller.sh $(module)
       echo "##vso[task.setvariable variable=DEBUG_FILES_NAME]$(echo $(module) | tr -dc '[:alnum:]\n\r')-$(date +%s)"
+      mkdir -p $DEBUG_FILES || { echo "FAILURE: cannot create log directory '${DEBUG_FILES}'." ; exit 1; }
+
+      ${{parameters.environment}} ./tools/ci/test_controller.sh $(module)      
     displayName: Test - $(module)
     env:
       IT_CASE_S3_BUCKET: $(SECRET_S3_BUCKET)
